// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gnvahoosychmrxodbipx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdudmFob29zeWNobXJ4b2RiaXB4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEzMTI4MjcsImV4cCI6MjA2Njg4ODgyN30.KyPdVOKgTmDAazLGFTPeg6LKByJle6X_Nddl3cL1AJo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});